Add Vector and Matrix compare, equal and equals with epsilon parameter
romainguy/kotlin-math pull request #48
Opened 2022-06-30 21:49 UTC by ThomasGorisse

2022-07-15 20:40 UTC, romainguy requested changes

2022-07-15 20:40 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Matrix.kt
> +inline fun compare(a: Mat2, b: Float, eps: Float? = null): Mat2 {
You could just write 
```
) = Mat2(
   ...
)
```
instead

2022-07-15 20:40 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Matrix.kt
> +inline fun compare(a: Mat2, b: Float, eps: Float? = null): Mat2 {
The compare methods should be called compareTo() to match Java/Kotlin

2022-07-15 20:40 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Quaternion.kt
> +inline fun compare(a: Quaternion, b: Float, eps: Float? = null) = compare(normalize(a).xyzw, b, eps)
Why are you normalizing before the tests?

2022-07-15 20:40 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Vector.kt
> +inline fun compare(a: Float, b: Float, eps: Float? = null): Float = when {
Use https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-float/compare-to.html instead. Or at least write a version that supports NaN properly:

```
        if (a > b) return 1
        if (a < b) return -1

        return a.toBits().compareTo(b.toBits())
```

2022-07-15 20:40 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Vector.kt
> +inline fun equals(a: Float, b: Float, eps: Float?): Boolean {
Don't make eps nullable, it causes boxing. Set it to 0.0f by default.

2023-02-08 23:40 UTC, ThomasGorisse commented
"J'ai enfin revu ma copie!"

Sorry for the late. I was in the middle of an onboarding and didn't had time for it before.

2023-02-09 00:57 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Vector.kt
> +        xyz.compareTo(v, delta),
See below, you are creating too many objects for no reason

2023-02-09 00:59 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Quaternion.kt
> +inline fun lessThan(a: Quaternion, b: Float) = lessThan(a.xyzw, b)
Each .xyzw creates a new vector

2023-02-09 00:59 UTC, romainguy commented on src/commonMain/kotlin/dev/romainguy/kotlin/math/Quaternion.kt
> +inline infix fun Quaternion.lt(b: Float) = xyzw.lt(b)
Same here: Each .xyzw creates a new vector

2023-02-09 01:02 UTC, merged